apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: socket-hello-server
    newName: 114614701236.dkr.ecr.ap-south-1.amazonaws.com/socket-hello-server
    newTag: sha-INITIAL   # CI overwrites this every push


    # 114614701236.dkr.ecr.ap-south-1.amazonaws.com/socket-hello-server