apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: code-executor-api
  newName: 114614701236.dkr.ecr.ap-south-1.amazonaws.com/code-executor-api
  newTag: sha-928eed7
secretGenerator:
- literals:
  - JWT_SECRET_KEY=change-this-to-a-real-secret
  name: code-executor-secrets
  options:
    disableNameSuffixHash: true
