apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-code
  namespace: code-exec
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: gp3
  resources:
    requests:
      storage: 2Gi